### ISSUE TITLE
Doc suggestions

### ISSUE THREAD

**Issue by gaumondp** [Kephson/reint_filelist_extended#1]
Quick suggestions in the "what does it do" section : 
1. Show some URLs before & after installing the extension.
2. I presumed it doesn't impact images from templates and visual in general. It could be specified.
3. Was it tested with RealURL ?

And the GIT repository looks like it hasn't been updated (TER is 1.0.1) and GIT refer to 0.5 version.

Just trying to be helpful. :)

**Comment by Kephson** [comment]
Hi, 
thanks for the report. 
But I think your questions are for the extension reint_file_timestamp and not for reint_filelist_extended?? -> https://github.com/Kephson/reint_file_timestamp

If this was the wrong repository, please add your issue in the correct repo. Thanks.

**Comment by gaumondp** [comment]
Sorry, you are correct, wrong depot and that explain the versionning "problem".
